language: python
python:
  - "3.7"
  - "3.8"
install:
  - python -m pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run coverage run -m pytest

after_sucess:
  codecov